### ISSUE TITLE
cpp-dotenv does not resolve variables in the .env

### ISSUE THREAD

**Issue by Vi1i** [adeharo9/cpp-dotenv#3]
Example:
```bash
DIRECTORY="/home/user/dir"
DATA_VERSION="v2"
4SQ_DIRECTORY="${DIRECTORY}/4sqForGoodDataset"
```
When bringing in the environment, the `${DIRECTORY}` does not resolve.

**Comment by adeharo9** [comment]
I've focused myself on solving many problems that the parser still had lately. Once I'm sure it parses everything right and there are no errors, I'll work on this since it'd be just absolutely complete to have this feature too.

**Comment by adeharo9** [comment]
I'm adding these feature to the update on the parser. Once I have it rewritten it'll be much easier to add.

**Comment by Vi1i** [comment]
Do you need other help on this project?

**Comment by adeharo9** [comment]
Right now it depends on how difficult it is to make the transition to ANTLR; from my past experiences, it shouldn't be much of a problem (although I think it is still too early to say).

However, I'll probably need to start adding some tests to the project, since there are many different situations to cover now and manual testing is not an option anymore (specially because of some platform-specific code fruit of #15 that needs to be tested). Any help on those would be much appreciated.

**Comment by adeharo9** [comment]
Implemented (and slightly tested).

Already merged to the `dev` branch, waiting for the next merge to `master`.

Closing the issue meanwhile.

**Comment by Vi1i** [comment]
I appreciate the work
